// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD60amN-Lvl2Vys-i35k7leS7HasbmutiE',
    appId: '1:861385729386:web:23fa41b50ab63caa947113',
    messagingSenderId: '861385729386',
    projectId: 'todo-flutter-clone',
    authDomain: 'todo-flutter-clone.firebaseapp.com',
    storageBucket: 'todo-flutter-clone.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKiiXNYX7i-0O2S4rCJfy8IAS7pHni_y4',
    appId: '1:861385729386:android:ea9da3f6c65dc6e9947113',
    messagingSenderId: '861385729386',
    projectId: 'todo-flutter-clone',
    storageBucket: 'todo-flutter-clone.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD60amN-Lvl2Vys-i35k7leS7HasbmutiE',
    appId: '1:861385729386:web:b0f81e35c7e794a7947113',
    messagingSenderId: '861385729386',
    projectId: 'todo-flutter-clone',
    authDomain: 'todo-flutter-clone.firebaseapp.com',
    storageBucket: 'todo-flutter-clone.firebasestorage.app',
  );
}
